name: Bank Transaction Analyzer
description: A finance transaction dashboard built with Streamlit.
topics:
  - streamlit
  - finance
  - banking
  - python
  - data-analysis
  - fintech
  - visualization
  - transactions
